Adiciona testes para validar o fluxo de boleto bancário
claudiosmweb/woocommerce-pagarme pull request #93
Opened 2019-04-11 20:02 UTC by murilohns

Esse PR adiciona teste para o fluxo de finalização de pedido utilizando boleto bancário.

Para que o teste funcione, ao finalizar uma compra com boleto bancário são feitas as seguintes validação:

1. Wordpress precisa estar na página de compra finalizada.
2. A página deve conter o texto "Pedido recebido" - Etapa baseada no tema `storefront`
3. A página deve conter um botão com o link para o boleto bancário - Em teste sempre será `https://pagar.me`

2019-04-12 13:13 UTC, leonampd requested changes

2019-04-12 13:13 UTC, leonampd commented on .circleci/config.yml
> +            - woopagarme-{{ .Branch }}-{{ checksum "composer.json" }}
Tava pensando e dado que o parametro `Branch` vai gerar um cache pra cada novo branch que subirmos, na prática não vamos estar aproveitando a feature. Dado que a gente não deve mudar muito acho que podemos remover o parâmetro e aproveitar o cache em builds diferentes e, sempre que for preciso invalidar o cache por algum motivo a gente muda a chave.

2019-04-12 13:13 UTC, leonampd commented on Makefile
> +e2e-cypress:
Acho que podemos mudar o nome do comando aqui pra `test-e2e`

2019-04-12 14:34 UTC, otaviopace commented on tests/e2e/support/checkoutOrder.js
> +const fillFormData = function() {
Aqui poderia ser uma `arrow function` que nem as outras funções 🙂

2019-04-12 14:36 UTC, otaviopace commented on tests/e2e/support/index.js
> +import './commands'
É necessário esse `import`, considerando que esse arquivo tem apenas comentários?
Isso é mais para já deixar pronto pro futuro? Não entendi muito bem, se puderem explicar por favor.

2019-04-15 13:22 UTC, leonampd approved these changes

2019-04-15 13:23 UTC, leonampd requested changes
Na verdade falta ajustar a mensagem do último commit @murilohns @ahmarcia. Feito isso podemos seguir em frente.

2019-04-15 13:54 UTC, leonampd approved these changes

2019-04-15 13:58 UTC, murilohns commented on tests/e2e/support/index.js
> +import './commands'
Sim, é necessário esse `import`

Com ele, todas as funções declaradas em `./commands` poderão ser utilizadas em nossos arquivos de teste

2019-04-15 14:00 UTC, otaviopace commented on tests/e2e/support/index.js
> +import './commands'
Sim, isso eu entendi, mas porque tem esse setup se é tudo comentário nesses arquivos?

2019-04-15 14:02 UTC, murilohns commented on tests/e2e/support/index.js
> +import './commands'
Ah, dá uma olhada no arquivo `commands.js` de novo, colocamos funções para facilitar nossos testes nele =]

2019-04-15 14:55 UTC, otaviopace commented on tests/e2e/support/index.js
> +import './commands'
Ahh, agora vi, beleza!

2019-04-15 14:55 UTC, evaporei approved these changes

2019-04-15 14:58 UTC, merged